# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# YAML configuration
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
template: !include templates.yaml
group: !include groups.yaml

# Proxy configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# My own handmade automations
automation manual: !include_dir_merge_list automations/

# Automations I create in the UI
automation ui: !include automations.yaml

# Notification Grouping
notify:
  - name: bom_devices
    platform: group
    services:
      - service: mobile_app_boms_iphone
      - service: mobile_app_boms_ipad